### ISSUE TITLE
add support for Hot Module Replacement

### ISSUE THREAD

**Issue by thescientist13** [kenzanlabs/react-webpack-stack#25]
HMR should be added as part of the `develop` workflow.

**Comment by thisgeek** [comment]
@thescientist13 Include support for style HMR, right?

**Comment by thescientist13** [comment]
@thisgeek 
Yes please!  Chances are you will likely want to implement (test) this when @cxoltero is complete and merged PRs related to #3 , which should be no later than EOD today

**Comment by thisgeek** [comment]
The way I'm activating HMR, the inline mode not working. Looking for others with this problem.

**Comment by thisgeek** [comment]
More specifically, when I activate HMR, I try the following:

1. Add a style to bootstrap.scss. Check if the style changes in the browser.
2. Make a meaningful change (e.g. not a comment) to bootstrap.tsx. Check if the browser updates.

Test 1 fails, and test 2 succeeds. Test 1 gets a lot of things right, though. Webpack automatically recompiles successfully, and I can see the browser make a request to a `hot-update.json` in the course of the change.

I would guess that something's amiss with the style-loader configuration. I'll start searching on that assumption.

**Comment by thisgeek** [comment]
Sorry for accidentally closing and reopening.

**Comment by thescientist13** [comment]
thanks for looking into this, @thisgeek !

**Comment by thisgeek** [comment]
And now the problem has magically disappeared. I'm almost disappointed.

I am following up with further testing. If it's good I'll request a pull.

**Comment by thisgeek** [comment]
Trouble with the style HMR was with the ExtractTextPlugin which doesn't support HMR. Moving that part of the configuration to the production config solves it (I say without having vigorously tested yet).

Still not done though. Changes to the tsx files still cause a refresh.

**Comment by thisgeek** [comment]
https://github.com/krausest/ts-webpack-hmr has a configuration with webpack 3 and TypeScript 2.4 that shows a working example of HMR with TypeScript, so I figure that either this project's configuration is slightly off or another plugin is getting in the way. Next step: disable some configuration parts until the HMR starts working.

**Comment by thisgeek** [comment]
Saw some recent changes to the webpack config. Rebased the branch, but no change in the broken HMR behavior. Moving on.

**Comment by thisgeek** [comment]
Installing react-hot-loader looks like it does the trick. Possibly there was nothing wrong with the typescript hot loading after all.
